### ISSUE TITLE
Enable reuse of GitHub Actions workflows somehow (completed 💚)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/module-requests#128]
Code reuse across workflows is impossible, we're copy-pasting across repositories and this isn't ok. I don't know when/if GitHub will allow workflow reuse like with GitHub Actions: https://github.com/actions/runner/issues/748

Is this something that can be done in userland? For example:

```yml
# .github/workflows-template/test.yml
apply:
  name: fregante/gh-workflow-npm-test@hash124
  with: # If `gh-workflow-npm-test` has any custom/conditional features, `with` acts as parameters
    node-version: [8.x, 10.x, 12.x]
jobs:
  test:
    env:
      MY-COOL-ENV: an amazing project
```

or 

```yml
jobs:
  test:
    name: Let's test stuff
    apply: fregante/gh-workflow-npm-test@hash124#jobs.test # It would only merge the specific jobs.test section
  build:
    needs: test
    steps:
      - run: echo My other steps
```

Then, on `npm install` or some other event, this module will:

1. look files under `.github/workflows-template/*.yml` 
2. download the specified workflows from GitHub
2. merge the user's template with the specified workflow(s), applying any special variables it expects like `node-version`
3. save the merged workflow as `.github/workflows/$1.yml`

This is pretty simple, but I need your suggestions on when/how to ensure that `.github/workflows/$1.yml` is up to date:

- via `postinstall` only?
- git hooks?

**Comment by fregante** [comment]
Such `gh-workflow-npm-test` would look like:

```json
{
  "name": "gh-workflow-npm-test",
  "scripts": {
    "postinstall": "gh-workflow"
  },
  "dependencies": {
    "gh-workflow": "0.0.0"
  }
}
```

```yml
name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: $node-version

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
```
