### ISSUE TITLE
Auto-publish npm packages

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/module-requests#73]
Like with https://github.com/sindresorhus/module-requests/issues/66 and https://github.com/sindresorhus/refined-github/pull/172, npm packages could be published automatically on travis by just adding a new git tag.

**Comment by jamestalmage** [comment]
I had this thought to.

But, it's already really easy to publish to `npm` via a CLI, and easy to share publish rights as well. Tools like `cut-release` and `np` make publishing just as easy as `git tag`.

Also, with `npm`'s interconnected nature (who knows how big your dependents graph is) - it's really important that *all* your CI runs pass before you publish a new version.

**Comment by bfred-it** [comment]
Yeah, it'd still have to pass the tests before publishing.

It _is_ is to publish with `np` but I still have to locate the project on my computer, open terminal, hope I don't have any WIP, pull, and then run `np`... as opposed to: open `github.com/your-name/your-module/releases/new`, type your version, click publish.

Not a big difference, but still it'd be nice :D

**Comment by parro-it** [comment]
@jamestalmage  - I think the idea here is to automate the publish without using a console at all, e.g. someone publish a PR (maybe a simple one, e.g. to correct a typo).

Normal CI on travis will run against the PR, you merge, you tag a new release on GH and Travis will publish on npm.

This should be easily done right now by using Travis deploy:

in .travis.yml:

```yaml
deploy:
  provider: releases
  api_key:
    secure: <GH token>
  skip_cleanup: true
  file: <a file to attach to the release in GH if needed>
  on:
    tags: true
after_deploy:
  - np $TRAVIS_TAG
```
